#!/usr/bin/perl

package MaDAME::Engine::MusDat::GetHandler;

use strict;
use warnings;

use MaDAME::Configuration;
use MaDAME::Log;
use MaDAME::Engine::MusDat::CalcHandler::KeyFinder;
use MaDAME::Engine::MusDat::CalcHandler::Scale;
#use MaDAME::Engine::MusDat::CalcHandler::Chord;

sub new {
    my $class = shift;
    my $self = {
        request => shift,
           data => shift,
    };
    bless $self, $class;
    
    return $self;
}

# Validate Data.

# Get instructions for data processing.
sub getData {
    my ( $self ) = shift;
    my @notes = @{ $self->{data} };
    my $request = $self->{request};
    
    my $data;

    if($request eq 'KeyFinder') {
        my @tmpdata = keyFinder(@notes);
        $data = \@tmpdata;
    }

    return $data;
}

sub keyFinder {
    my @notes = @_;
    my @keys = &MaDAME::Engine::MusDat::CalcHandler::KeyFinder::getKey(@notes);
       
    for my $key (@keys) {
        my $tmp = $key;
        $key = {
                   name  => $tmp,
		   scale => [&MaDAME::Engine::MusDat::CalcHandler::Scale::findScale($tmp)],
        };     
        debug("scale in key $tmp is " .  join(', ', @{ $key->{scale} }) );
    }
    return @keys;
}
# Execute instructions.

# Check output

# Return output suitable for MaDAME::Data to begin conversion to e.g. MusicXML.

1;
